# Generated by Django 3.0 on 2022-04-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authenticate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('auth_otp', models.CharField(max_length=30)),
                ('is_verify', models.BooleanField(default=False)),
                ('is_created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
