# Generated by Django 3.0 on 2022-04-29 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_auto_20220426_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='images/sample.jpg', upload_to='images/product/'),
        ),
    ]
